name: beejx
description: "A Project for helping Indian Farmers"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  qr_flutter: ^4.1.0
  http: ^1.6.0
  record: ^6.0.0
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  dio: ^5.1.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_tts: ^4.0.2
  mediapipe_genai: ^0.0.1
  audioplayers: ^6.0.0
  connectivity_plus: ^6.0.3
  percent_indicator: ^4.2.3
  google_fonts: ^6.1.0
  device_info_plus: ^10.1.0
  tflite_flutter: ^0.12.1
  image: ^4.1.3
  flutter_animate: ^4.5.0
  firebase_core: ^3.6.0
  firebase_database: ^11.3.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.3
  speech_to_text: ^7.0.0
  image_picker: ^1.0.7
  firebase_storage: ^12.3.0
  cloud_firestore: ^5.4.0
  fl_chart: ^0.68.0
  sqflite: ^2.3.2
  path: ^1.9.0
  supabase_flutter: ^2.12.0
  google_generative_ai: ^0.4.0
  firebase_messaging: ^15.0.0
  flutter_markdown: ^0.7.1
  llama_cpp_dart: ^0.2.2 
  onnxruntime:
  uuid: ^4.5.2
  crypto: ^3.0.7
  file_picker: ^10.3.8
  provider: ^6.1.5+1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/crops_data.json
    - assets/mobilebert.tflite
    - assets/model.tflite
    - assets/labels.txt
    - assets/background.png
    - assets/icon.png
    - assets/soil_data.json
    - assets/.env
    - assets/onboarding1.png
    - assets/onboarding2.png
    - assets/onboarding3.png
    # - assets/fonts/ # specific fonts if added

